# Generated by Django 5.0.4 on 2024-04-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bruger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('addressLine1', models.CharField(max_length=255)),
                ('addressLine2', models.CharField(max_length=255)),
                ('zipCode', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=255)),
                ('vatNumber', models.CharField(max_length=20)),
                ('orderComment', models.TextField()),
                ('cart', models.TextField()),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('termsAccepted', models.BooleanField()),
                ('receiveMarketing', models.BooleanField()),
            ],
        ),
    ]
